#/usr/bin/python
#-*-coding:utf-8-*-

from selenium import webdriver
from time import sleep
dr = webdriver.Chrome()
dr.get('https://mail.qq.com/')
sleep(2)
dr.maximize_window()
sleep(2)
def DL ():
    dr.switch_to.frame('login_frame')
    dr.find_element_by_xpath('//*[@id="switcher_plogin"]').click()
    sleep(2)
    dr.find_element_by_id('u').send_keys('3202037092')
    sleep(2)
    dr.find_element_by_id('p').send_keys('hnzdzjb68924293')
    sleep(1)
    dr.find_element_by_xpath('//*[@id="login_button"]').click()
    sleep(3)
    print('登录成功')
def XX():
    dr.find_element_by_xpath('//*[@id="composebtn"]').click()
    sleep(1)
    dr.switch_to.frame('mainFrame')
    sleep(2)
    # dr.find_element_by_xpath('//*[@id="to_btn"]').click()
    # sleep(5)
    dr.find_element_by_xpath("//*[@id='toAreaCtrl']/div[2]/input").send_keys('1073795138@qq.com')
    sleep(5)
    dr.find_element_by_id('subject').send_keys('test')
    sleep(2)
    dr.switch_to.default_content()
    dr.switch_to.frame("mainFrame")
    sleep(0.5)
    Body_frame = dr.find_element_by_class_name("qmEditorIfrmEditArea")
    dr.switch_to.frame(Body_frame)
    sleep(2)
    dr.find_element_by_xpath('/html/body').send_keys("I LOVE Python")
    sleep(3)
    dr.switch_to.parent_frame()
    dr.find_element_by_xpath('//*[@id="toolbar"]/div/a[1]').click()
    sleep(5)
    dr.quit()
    print('发送成功')
DL()
XX()
